version: '3'

services:
  node-test:
    build: .
    depends_on:
      - mongo
      - mongo-express
    environment:
      - mongohost=mongo
    command: npm test

  node-demo:
    build: .
    depends_on:
      - mongo
      - mongo-express
    environment:
      - mongohost=mongo
    ports:
      - 8080:8080

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example