FROM node:10.11.0-alpine

WORKDIR /calendly

COPY ./package.json ./
COPY ./package-lock.json ./
RUN npm install

COPY ./app ./app
COPY server.mjs ./

COPY ./tests ./tests

ENV mongohost=mongo

EXPOSE 8080

CMD ["npm", "start"]
